<?xml version="1.0" encoding="UTF-8"?>
<Project>

  <PropertyGroup>
    <Msfs2024SdkPath>$([MSBuild]::EnsureTrailingSlash('$(MSFS2024_SDK)'))</Msfs2024SdkPath>
  </PropertyGroup>
  <PropertyGroup>
    <Msfs2024SdkVersionFileContents>$([System.IO.File]::ReadAllText('$([MSBuild]::EnsureTrailingSlash('$(MSFS2024_SDK)'))version.txt').Trim())</Msfs2024SdkVersionFileContents>
    <Msfs2024SdkVersion>$([System.Text.RegularExpressions.Regex]::Match('$(Msfs2024SdkVersionFileContents)', '^\d+\.\d+\.\d+(?:\.\d+)?').Value)</Msfs2024SdkVersion>
  </PropertyGroup>

</Project>
